services:
  attacker:
    image: ubuntu:24.04
    command: sleep infinity
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./sploit.py:/lab/sploit.py:ro

  attacker_default:
    image: ubuntu:24.04
    command: sleep infinity
    volumes:
      - ./sploit.py:/lab/sploit.py:ro

  victim:
    image: ubuntu:24.04
    command: sleep infinity
