services:
  attacker:
    image: quay.io/jupyter/base-notebook:latest
    command: >
      start-notebook.py
      --ServerApp.ip=0.0.0.0
      --ServerApp.token=attacker
      --ServerApp.password=''
      --ServerApp.allow_root=True
    security_opt:
      - seccomp:unconfined
    user: root
    ports:
      - "8888:8888"

  victim:
    image: quay.io/jupyter/base-notebook:latest
    command: >
      start-notebook.py
      --ServerApp.ip=0.0.0.0
      --ServerApp.token=victim
      --ServerApp.password=''
      --ServerApp.allow_root=True
    user: root
    ports:
      - "9999:8888"
